version: '3'
services:

  postgres:
    container_name: cttcontainer
    image: "postgres:9.6.1"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cttdatabase

